### PR TITLE
"Don't Use Map Data" -> "Use Map Data" for clarity and consistency

### PR DESCRIPTION
**Pull request by shad0wshayd3**

### CODE REVIEW

**Comment by zilav** [comment]
This flag has the opposite meaning when set.

**Comment by shad0wshayd3** [comment]
It, like all of the other flags, are referring to the parent in the block that they belong to, e.g. `Use [...] Data (from parent)`. Compared to the CK, the meaning in xEdit is different, suggesting that the Cell/Worldspace is providing the data itself when this isn't the case.

<details>
 <summary>Comparison:</summary>

image
image
</details>

<details>
 <summary>Example of just xEdit:</summary>

image
</details>

**Comment by zilav** [comment]
IIRC when you have "Use Map Data" checked in CK, the flag is not set and vice versa. You are comparing different worldspaces on your screenshots. Make sure to check the actual values on the same worldspace after saving in CK to confirm that the flag is not inverted here.

**Comment by shad0wshayd3** [comment]
Those are the same worldspace, `AlftandWorld`. Here's a more complete view of the record to show it contains no `MNAM - Map Data`.
<details>
 <summary>Screenshot:</summary>

image
</details>

<details>
 <summary>And a comparison to the CK view of `WhiterunDragonsreachWorld`, from the above issue.</summary>

image
</details>

<details>
 <summary>And a comparison of a record where Use Map Data is not checked in the CK.</summary>

image
image
</details>

**Comment by shad0wshayd3** [comment]
<details>
<summary>Here's an example comparison for Fallout 4 with the flag</summary>

image
image
</details>

<details>
<summary>And Without</summary>

image
image
</details>

<details>
<summary>And, no CK comparison for 76, but a Worldspace with the flag, and no MNAM - Map Data</summary>

image
</details>

<details>
<summary>And a Worldspace without the flag, and MNAM - Map Data</summary>

image
</details>

**Comment by zilav** [comment]
Alright, maybe they changed it in one of the later patches. I definitely remember this flag being inverted in Skyrim initially.

**Pull request merged**
