### PR TITLE
Feature/GetExpectedSignatures

### PR DESCRIPTION
**Pull request by matortheeternal**
This PR adds a function to `IwbFormIDChecked` to retrieve allowed/expected signatures.  This functionality is used in [xedit-lib](https://github.com/matortheeternal/xedit-lib).  The function is used in [shampoo](https://github.com/matortheeternal/shampoo) to determine whether or not an unresolved reference (URR) can be replaced with a NULL reference without creating an unexpected reference error (UER).  I exposed the function to the jvInterpreter.

The function is useful in several circumstances including but not limited to:

- A script or external GUI needs to determine what references are allowed for a particular field to populate a reference list.
- A script or application needs to determine which references are allowed prior to setting a particular value.

### CODE REVIEW

**Comment by zilav** [comment]
What's the point in SignaturesText when there are already Signatures[] and SignatureCount properties?

**Comment by matortheeternal** [comment]
Good question.  I suppose it's more of a design choice than anything.  You could build a string by looping through the `Signatures` property, it just seems to be a bit cumbersome to me.  It's nice if I can just get the whole string all at once, as there's little reason for calling code to want a single signature.

Maybe for internal uses those properties are useful (when checking if a reference is valid), but if someone wants to know all of the valid signatures it's just a cumbersome extra-layer they have to work through.

**Comment by zilav** [comment]
Accessing valid signatures through already available array is not cumbersome, it is the right way to do especially since comparing TwbSignature is magnitudes faster. Right now you get the list only in 1 place - jvinterpreter function, and that is the place were string should be created if really needed.

**Comment by matortheeternal** [comment]
The use case which led me to create this function is I wanted to know whether or not a NULL reference was allowed for a particular element.  Like [this](https://github.com/matortheeternal/shampoo/blob/master/src/Services/errorsService.js#L147-L166), calling [this function](https://github.com/matortheeternal/xedit-lib/blob/master/src/xeElements.pas#L1081-L1103) from xedit-lib.

Based on your feedback it sounds like you think a better approach is to instead have a function which we can call with a particular signature to see whether or not that signature is allowed.  Like this: 

    function NativeGetSignatureAllowed(formDef: IwbFormIDChecked; sig: TwbSignature): WordBool;
    begin
      Result := False;
      for i := 0 to Pred(formDef.SignatureCount) do
        if formDef.Signatures[i] = sig then begin
          Result := True;
          exit;
        end;
    end;

    function GetSignatureAllowed(_id: Cardinal; sig: PWideChar; bool: PWordBool): WordBool;
    var
      element: IwbElement;
      integerDef: IwbIntegerDef;
      formDef: IwbFormIDChecked;
    begin
      Result := False;
      try
        if not Supports(Resolve(_id), IwbElement, element) then
          raise Exception.Create('Interface is not an element.');
        if not Supports(element.ValueDef, IwbIntegerDef, integerDef)
        or not Supports(integerDef.Formater[element], IwbFormID) then
          raise Exception.Create('Interface must be able to hold a FormID value.');
        if Supports(integerDef.Formater[element], IwbFormIDChecked, formDef) then
          bool^ := NativeGetSignatureAllowed(formDef, TwbSignature(AnsiString(sig))
        else
          bool^ := true;
        Result := True;
      except
        on x: Exception do ExceptionHandler(x);
      end;
    end;

That sounds reasonable to me.  Closing this.

**Pull request closed without merging**
