### PR TITLE
Added option to read files into memory for plugin hotloading

### PR DESCRIPTION
**Pull request by matortheeternal**
The CK supports plugin hotloading functionality, whereby a user can save changes to a plugin in the CK and then use the game's hotloading functionality to see the changes immediately.

xEdit in its current state can't do this because it uses memory mapping, so it's not possible to save over the original file.  This update adds a new optional boolean parameter to `TwbFile.Create`, `ReadIntoMemory`.  This parameter, when set, will use the new `flReadFile` procedure instead of `flOpenFile`, which in turn loads the file into a new `TwbFile` private member variable `flBuffer` using the Windows API `ReadFile` function.

### CODE REVIEW

**Comment by matortheeternal** [comment]
Still testing things, but decided to open the PR anyways to start discussion if necessary.

**Comment by zilav** [comment]
I thought about this in the past but decided not to implement because of limited usage of hot plugins reloading. It appeared only in Skyrim, it is very bugged and suitable only for limited type of plugins (those without persistent data), and can be always workarounded using "Save as" script if really needed.

**Comment by matortheeternal** [comment]
I'm implementing this at the request of Megaloblast, author of [NLVA](https://www.nexusmods.com/skyrim/mods/75346/?) and [Dolomite Weathers](https://www.nexusmods.com/skyrimspecialedition/mods/7895/?).  He has expressed an interest in being able to hotload plugins from xEdit/zEdit.

It's true that the save as script offers a workaround, which I was not aware of until just recently.  I'm still working no getting reading files into memory working properly, if I can't figure it out soon I may just offer that functionality in zEdit as well.

\- Mator

**Comment by matortheeternal** [comment]
Closing this because I decided to just go with what zilav recommended - it seems to work for Megaloblast.  I couldn't get reading the files directly into memory just to work properly after fiddling around with it for a bit, so I'm just going to recommend people use the workaround.

**Pull request closed without merging**
