### PR TITLE
Fixes for FO4 and FO76

### PR DESCRIPTION
**Pull request by eckserah**
Fix DNAM for QUST in FO76
Fix processing of SPED in RACE and MOVT for both FO4 and FO76 (uses the same structure)
Some new ADDN nodes use IKEK instead of DATA for the node index.
Second and third NEXT are not required in QUST for FO76

### CODE REVIEW

**Comment by Infernio** [comment]
How does the game differentiate between the `CTDA`s when no `NEXT` subrecords are present? I'm pretty sure that's the reason they were made required; see all the recent reports, e.g. #737 and #747, which deal with issues arising from duplicate subrecord arrays with no required subrecords between them.

**Comment by eckserah** [comment]
The game literally does not process any extra ctdas if the next for it isn't present. It actually doesn't process any ctdas at all if there are no next present. Not sure if fo4 does the same thing. My change was only for 76. I have not gotten into looking at skyrim as of yet and how that works.

**Comment by Infernio** [comment]
Ah, I see. That will be quite annoying to handle if WB ever gets FO76 support 😛

**Comment by ElminsterAU** [comment]
Do not remove the required from NEXT. I'm not going to merge that.
The different union members for SPED should all have the same number of members, so that the line up correctly side by side when comparing versions of the record with different form versions. use wbEmpty('Unused') to pad them as far as that's possible.

**Comment by ElminsterAU** [comment]
this PR is obsolete, the changes have already been otherwise included in dev-4.1.4 and dev-4.1.2. is now frozen after the release for version 4.1.3

**Pull request closed without merging**
