### PR TITLE
Feature/SortEditorIDs

### PR DESCRIPTION
**Pull request by matortheeternal**
This PR creates a new function `SortEditorIDs`.  The function allows a user, or other calling code, to load all records with a particular signature into the `flRecordsByEditorID` array that already existed for files.  This makes it possible to use `RecordByEditorID` effectively without having to build the entire EditorID map for a particular file, which can be very time consuming (>20 seconds for Skyrim.esm on my machine).  The function is exposed through the jvInterpreter so scripts can make use of it.

The code in this PR is depended on the `RecordsBySignature` function I added in my other PR.  The commits from that PR are included here.

### CODE REVIEW

**Comment by zilav** [comment]
What if there is a need to sort by several record types at once? Have to call SortEditorIDs function several times which performs full scan.
I see some point in speeding up EditorID index building when not all records are needed, but the right way to do that is probably to turn wbTrackAllEditorIDs into array of TwbSignature, automatically filled with all record types by default from definitions, and ability to modify it maybe through Options with persisting in settings file.

**Comment by matortheeternal** [comment]
The only issue with that approach is it doesn't allow iterative building, so the application needs to know the EditorIDs to sort prior to launching.

The point of this is to make it so if a user executes a script/tool which needs to access, say, ARMO records by EditorID, the script can simply instruct xEdit to sort ARMO record EditorIDs.  If xEdit already has them sorted it can do nothing, else it'd do the sorting then and there.  Yes, it is less efficient if a script wanted to sort a bunch of different things (perhaps I can allow the input to be a comma-separated string of EditorIDs?).

I don't see much of a use case for a user to tell xEdit to sort all EditorIDs for records of a particular signature for all files at load time.  The whole point is that at load time you don't know what EditorIDs other code will need to access, so you can either build all of it (which is very slow when including Skyrim.esm or other large plugin files), or build it iteratively on demand.  The total work necessary for iterative on demand building IS less, even if it may require more iterations through the records of a file.

**Comment by zilav** [comment]
Users don't care about EditorID index because it is not used anywhere. The only purpose of it's existence is to speed up matching of GMST overrides. It also indexes FLST by default only because there are some test functions left in xEdit frmViewMain code which deals with them using EditorIds.

EditorIDs index benefits only scripts, and only if they use particular function MainRecordByEditorID(). That's why Hlp added a single boolean wbTrackAllEditorID option, it is more than enough to satisfy a few scripts. The same way some scripts require references index which also takes time to build, much more time than EditorIDs.

**Comment by matortheeternal** [comment]
> That's why Hlp added a single boolean wbTrackAllEditorID option, it is more than enough to satisfy a few scripts. 

It's total overkill.  Building it iteratively as demanded by scripts is much more efficient and reasonable.

**Comment by zilav** [comment]
Iterative building is less efficient as I already mentioned. Reasonable is a subjective opinion because it is unresonable for me for example. If scripts work extensively with records using their Editor IDs, then building the entire index is the way to go because... why not.
20 seconds delay is more than reasonable for an ordinary user to wait for in application that is going to be executed once a few days. xEdit takes much more than that to launch by default with all automatic refs building on DLCs. And CK takes even more.

**Comment by matortheeternal** [comment]
> Iterative building is less efficient as I already mentioned.

Only if the session requires sorting a large portion of the records in the file.  If a small portion is required it is dramatically more efficient, as I already mentioned.  This should be the case 95% of the time in real world use cases.

> If scripts work extensively with records using their Editor IDs, then building the entire index is the way to go because... why not.

What kind of argument is that?  Why not: it takes a long time.  What is the likelihood that a script actually needs to access records of every signature from every file?  I can't think of ANY real world script which would need to do that.  Even if there was such a script, 99% of all scripts don't need that, so it's moot.

> 20 seconds delay is more than reasonable for an ordinary user to wait for in application that is going to be executed once a few days.

So losing 219 nanoseconds per RecordByFormID call is "too much", but losing 20 whole seconds every time the program starts is OK?  You're being incredibly inconsistent.  It sounds to me like you're just coming up with excuses to not merge my changes.

> xEdit takes much more than that to launch by default with all automatic refs building on DLCs.

Which you can skip by holding shift when clicking OK, which is something that I do every time I start xEdit and believe should be default behavior because the majority of use cases xEdit is used for does not require refs to be built for all files.  It's also "hidden" functionality and bad UX for that matter.

Also, you're once again excusing a large time suck for it being "insignificant" at the level of an individual user.  I think this is a fallacious line of reasoning because xEdit is used by over a million users.  If those million users start xEdit an average of 5 times, that's 27,777 wasted user hours.

> And CK takes even more.

How is another program being worse and a greater time suck a good reason to not address this?

**Comment by zilav** [comment]
I see no connection between "xEdit is used by over a million users", "wasted user hours" and the topic of EditorID index building itself since users don't benefit in any way from it's existence. Only you do because me and Hlp are happy to build the entire index when our scripts require it.

I added Shift key as a personal hidden hack (and I'm probably going to limit it to debug mode only), it was never meant to be used by others because xEdit must always build references to guarantee data integrity in plugins no matter how much time it "wastes" or majotiry of use cases.

CK is not worse, it is different.

**Pull request closed without merging**
