### PR TITLE
wbBinarySearch

### PR DESCRIPTION
**Pull request by matortheeternal**
This is a refactor which moves the binary searching which is used in several methods to its own generic function, similar to `wbMergeSort`.  The function lives in `wbImplementation`.

The following functions are adjusted to the new function, `wbBinarySearch`:

- TwbFile.FindEditorID
- TwbFile.FindFormID
- TwbFile.FindInjectedID
- TwbContainer.FindBySortKey
- TwbMainRecord.FindReferencedBy

Tested in my local development environment.

The different search comparators are implemented through a TSearchCompare function reference type.  The design is largely inspired by the design of wbMergeSort (although with no asm bits).  The code could potentially be moved into the wbSort unit.

Previously, if `flFormIDsSorted` was `False` for a file and some other code called RecordByFormID it would simply exit, though there was code present for doing a "slow" iterative search.  I added a new global configuration variable to wbInterface `wbAllowSlowSearching` which will allows this code to be reached if set to true.  The variable is `False` by default, so default behavior of the program is unchanged.

### CODE REVIEW

**Comment by zilav** [comment]
First - just a nitpicking, but I don't like chosen names. SeachBy* functions better to rename to CompareEditorID, CompareFormID, etc., and SearchByRecord to CompareFormIDandLoadOrder to reflect what they really do since they don't perform the searching itself. Also there is already CompareSparseName() function which kind of sets the obvious naming scheme. And wbAlsoSlowSearch -> wbSearchUnsortedFormID or something like that.

Second - speed concerns. This refactoring adds a call per iteration, we are talking about extra thousands of calls in the worst case when searching in the game master file which usually contains around 1 mil of records. Did you perform any speed comparisons? For example selecting 100000 random records and getting them by FormID from a file.

**Comment by matortheeternal** [comment]
I will adjust the names per your suggestions.  My main motivation for not using "Compare" functions is because I did not want to confuse the functions with the Compare functions that are used with `wbMergeSort`, because although the functions have the same signature, the expected types stored in the pointers provided is different (the first is often an IwbMainRecord, but the second is often a value type like String or Cardinal).

I will perform some benchmarks shortly and provide you with the results.

**Comment by matortheeternal** [comment]
##Benchmarks

First, just loading xEdit and building references for Skyrim and all DLCs, (3 tests):

**Before my changes**

    [00:23:686] Background Loader: finished
    [00:22:607] Background Loader: finished
    [00:22:774] Background Loader: finished

**After my changes**

    [00:22:714] Background Loader: finished
    [00:22:682] Background Loader: finished
    [00:22:685] Background Loader: finished

---

Second, I ran an xEdit script for random FormID access, the code for that script is below:

    unit userscript;

    const
      FormIDCount = 1000000; // TODO: Increase

    procedure SelectRandomFormIDs(f: IInterface; var lst: TList);
    var
      i, n: Integer;
    begin
      AddMessage('Selecting random FormIDs');
      for i := 1 to FormIDCount do begin
        n := Random(RecordCount(f));
        lst.Add(GetLoadOrderFormID(RecordByIndex(f, n)));
      end;
    end;

    procedure BenchmarkAccess(f: IInterface; var lst: TList);
    var
      i: Integer;
      start: TDateTime;
    begin
      AddMessage(Format('Started benchmark %s', [Now]));
      start := Now;
      for i := 0 to Pred(lst.Count) do
        RecordByFormID(f, Integer(lst[i]), true);
      AddMessage(Format('Completed %s', [Now]));
    end;

    function Initialize: integer;
    var
      dragonborn: IInterface;
      lst: TList;
    begin
      dragonborn := FileByIndex(4);
      lst := TList.Create;
      SelectRandomFormIDs(dragonborn, lst);
      BenchmarkAccess(dragonborn, lst);
    end;

    end.

I did try to format the date string to get milliseconds, but was unable to do so.

**Before my changes**  

    Applying script...
    Selecting random FormIDs
    Started benchmark 6/8/2017 11:59:09 AM
    Completed 6/8/2017 11:59:27 AM
    [Apply Script done]  Processed Records: 0, Elapsed Time: 00:57

**After my changes**

    Applying script...
    Selecting random FormIDs
    Started benchmark 6/8/2017 12:05:14 PM
    Completed 6/8/2017 12:05:32 PM
    [Apply Script done]  Processed Records: 0, Elapsed Time: 00:59


## Conclusions

If you observe the benchmarks closely you will note that there is no determinable difference in performance.

This makes sense because the performance requirement of a single function call is irrelevant in the context of the other code which is executed.  Yes, a binary search is fast, operating in `O(log2(n))` time but it is still large enough to make the cost of a function frame irrelevant.

**Comment by matortheeternal** [comment]
Because I didn't like how the jvInterpreter muddies the results of this benchmark, I created a native benchmark as well, simply executing a native function through the jvInterpreter:

    procedure TfrmMain.BenchmarkRecordByFormID(Args: TJvInterpreterArgs);
    var
      _File: IwbFile;
      FormIDCount, i: Integer;
      FormIDs: array of Cardinal;
      start, completed: Cardinal;
    begin
      if not Supports(IInterface(Args.Values[0]), IwbFile, _File) then
        exit;
      AddMessage('Benchmarking RecordByFormID');
      FormIDCount := Integer(Args.Values[1]);
      AddMessage('Selecting ' + IntToStr(FormIDCount) + ' random FormIDs');
      SetLength(FormIDs, FormIDCount);
      for i := Low(FormIDs) to High(FormIDs) do
        FormIDs[i] := _File.Records[Random(_File.RecordCount)].LoadOrderFormID;
      AddMessage('Benchmarking access');
      start := GetTickCount;
      for i := Low(FormIDs) to High(FormIDs) do
        _File.RecordByFormID[FormIDs[i], True];
      AddMessage(Format('Benchmark completed in %0.3fs', [(GetTickCount - start) / 1000.0]));
    end;

**Before my changes**

    Applying script...
    Benchmarking RecordByFormID
    Selecting 1000000 random FormIDs
    Benchmarking access
    Benchmark completed in 0.577s

**After my changes**

    Applying script...
    Benchmarking RecordByFormID
    Selecting 1000000 random FormIDs
    Benchmarking access
    Benchmark completed in 0.796s

This shows a more measurable change in performance.  The cost appears to be `219ns` per function call on my machine.  The overall slowdown appears to be 37.9%.  I think the improvement in architecture outweighs this performance cost which will be absolutely imperceptible in all usages of xEdit that I am aware of.  If there is a need for greater performance I would recommend inlining the function or converting it to assembly.

**Comment by zilav** [comment]
That's actually a noticable degradation for a small unimortant refactoring. I don't see this as improvement in architecture because it simply refactors 3 separated sorted code fragments into a single procedure (and they are inlined now most likely because of performace concerns).
If you really need to search in unsorted record arrars, I recommend to implement this with conditional {DEFINE} and {IFDED} compiler directives instead of variable, code will look almost the same without any speed loss.

**Comment by matortheeternal** [comment]
That's fine, I just made the change because I thought it was a good architecture decision.  I can't think of any real-world scenario where those `219ns` per `RecordByFormID` call would be significant, but it's ultimately up to you to make the decisions.  If you become interested in this PR in the future feel free to re-open it or improve it, but for now I'll just close it.

**Pull request closed without merging**
