### PR TITLE
Feature/RecordsBySignature

### PR DESCRIPTION
**Pull request by matortheeternal**
This PR adds a simple function for getting all records with a particular signature from a file.  The function is exposed through the `jvInterpreter`.  I am aware that this can be accomplished with the existing function `wbGetSiblingRecords`, but I feel the lack of a member function on `IwbFile` is a bit of an oversight for other considerations (see my other PR).

I also feel that the functionality offered by this and `wbGetSiblingRecords` are suitably different to warrant both functions being present.  Getting records by signature is especially important for patching, and the lack of a function explicitly named for this functionality is not user friendly for that use case.

### CODE REVIEW

**Comment by zilav** [comment]
1. All signatures are passed as TwbSignature type internally in xEdit code, not as a string
2. Your function won't work for CELL record obviously
3. Allocate array memory by doubling existing length, not by linear incrementations. SetLength() is a very costly operation because if memory block can't be reallocated at the same position which is very likely to happen, it will a) allocate the new one; b) copy content of old block to new; c) deallocate old block.

**Comment by matortheeternal** [comment]
> 1. All signatures are passed as TwbSignature type internally in xEdit code, not as a string

Will fix.

> 2. Your function won't work for CELL record obviously

Yeah, I was aware of this.  Was wondering if there was a generic way to check if a record exists both in child groups and as a top level group.  If not I just hardcode CELL in there.

> 3. Allocate array memory by doubling existing length, not by linear incrementations. SetLength() is a very costly operation because if memory block can't be reallocated at the same position which is very likely to happen, it will a) allocate the new one; b) copy content of old block to new; c) deallocate old block.

I did not know that. TIL.  I will make that change.  Perhaps it would be better for me to just not use iterative allocation and just allocate the maximum size for files as well, as it is a truly tiny amount of RAM in the end and requires no resizing operations (a file with 1,000,000 records would require allocating 4MB of RAM).

**Comment by zilav** [comment]
Up to you how to allocate mem, just don't do it in small linear incrementations.
Anyway I still don't understand the purpose of this function compared to wbGetSiblingRecords
It is either this
 `File.RecordsBySignature('ARMO')`
or that
`wbGetSiblingRecords(File.GroupBySignature('ARMO'), ['ARMO'])`
which has no difference to me, but the later is more flexible since you can scan any object (not only a file), and it will also work fine for CELL
`wbGetSiblingRecords(File, ['CELL'])`

**Comment by matortheeternal** [comment]
I agree.  I think that `wbGetSiblingRecords` is perhaps a better function for the job.  I initially created this function in large part because I forgot it existed.

I'm closing this PR but I do have a question -

Why is wbGetSiblingRecords not a member function on TwbContainer, and exposed through the IwbContainer interface?  I realize it only works with IwbFile, IwbGroupRecord, and IwbMainRecord interfaces, but still.  Why are certain functions offered in `wbHelpers` while other functions are made available through the interfaces?  Is it because the interfaces are too bloated or..?

**Comment by zilav** [comment]
Probably because it is not used by other API functions and only needed for specific external operations like LOD generation.

**Pull request closed without merging**
